<a href="https://colab.research.google.com/github/cenna-alias/test/blob/main/Student_Performance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1.	Download the Student Performance Prediction dataset from Kaggle.

In [55]:
from google.colab import files
uploaded = files.upload()

Saving Students Performance.csv to Students Performance (3).csv

# 2.	Import the required Python libraries.

In [56]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error,r2_score

# 3.	Load the dataset into a Pandas DataFrame.

In [57]:
df = pd.read_csv('Students Performance.csv')

# 4.	Display the first 5 and last 5 rows of the dataset.

In [58]:
df.head()

,Student_ID,Student_Age,Sex,High_School_Type,Scholarship,Additional_Work,Sports_activity,Transportation,Weekly_Study_Hours,Attendance,Reading,Notes,Listening_in_Class,Project_work,Grade
0,STUDENT1,19-22,Male,Other,50%,Yes,No,Private,0,Always,Yes,Yes,No,No,AA
1,STUDENT2,19-22,Male,Other,50%,Yes,No,Private,0,Always,Yes,No,Yes,Yes,AA
2,STUDENT3,19-22,Male,State,50%,No,No,Private,2,Never,No,No,No,Yes,AA
3,STUDENT4,18,Female,Private,50%,Yes,No,Bus,2,Always,No,Yes,No,No,AA
4,STUDENT5,19-22,Male,Private,50%,No,No,Bus,12,Always,Yes,No,Yes,Yes,AA

In [59]:
df.tail()

,Student_ID,Student_Age,Sex,High_School_Type,Scholarship,Additional_Work,Sports_activity,Transportation,Weekly_Study_Hours,Attendance,Reading,Notes,Listening_in_Class,Project_work,Grade
140,STUDENT141,19-22,Female,State,50%,Yes,Yes,Private,0,Always,No,Yes,No,Yes,CC
141,STUDENT142,18,Female,State,75%,No,No,Private,0,Never,No,Yes,Yes,No,CC
142,STUDENT143,18,Female,Private,75%,No,No,Private,0,Always,Yes,No,No,No,AA
143,STUDENT144,19-22,Female,State,75%,Yes,Yes,Bus,12,Sometimes,No,Yes,No,Yes,CB
144,STUDENT145,18,Female,Private,100%,No,No,Private,12,Always,Yes,No,Yes,No,BB

# 5.	Find the dataset shape (rows and columns).

In [60]:
df.shape

(145, 15)

# 6.	Display the column names and data types.

In [61]:
df.columns

Index(['Student_ID', 'Student_Age', 'Sex', 'High_School_Type', 'Scholarship',
       'Additional_Work', 'Sports_activity', 'Transportation',
       'Weekly_Study_Hours', 'Attendance', 'Reading', 'Notes',
       'Listening_in_Class', 'Project_work', 'Grade'],
      dtype='object')

In [62]:
df.dtypes

Student_ID            object
Student_Age           object
Sex                   object
High_School_Type      object
Scholarship           object
Additional_Work       object
Sports_activity       object
Transportation        object
Weekly_Study_Hours     int64
Attendance            object
Reading               object
Notes                 object
Listening_in_Class    object
Project_work          object
Grade                 object
dtype: object

# 7.	Check for missing values and handle them appropriately.

In [63]:
df.isnull().sum()

Student_ID            0
Student_Age           0
Sex                   0
High_School_Type      0
Scholarship           1
Additional_Work       0
Sports_activity       0
Transportation        0
Weekly_Study_Hours    0
Attendance            0
Reading               0
Notes                 0
Listening_in_Class    0
Project_work          0
Grade                 0
dtype: int64

# 8.	Check for duplicate records and remove them if any.

In [64]:
print(df.duplicated().sum())

0

# 9.	Generate descriptive statistics for the numerical columns.

In [65]:
df.describe()

       Weekly_Study_Hours
count          145.000000
mean             2.331034
std              4.249273
min              0.000000
25%              0.000000
50%              0.000000
75%              2.000000
max             12.000000

# 10.	Perform Exploratory Data Analysis (EDA) using suitable visualizations.